version: '3.8'

services:
  frontend:
    image: vatai12/worker-cabinet-frontend:latest
    container_name: worker-cabinet-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - worker-cabinet-network

networks:
  worker-cabinet-network:
    driver: bridge
