import { startRecording } from '../lib.mjs'

const r = await startRecording('vacation-approve', 'petrov@example.com')
const { page, pause, caption, moveTo, clickOn, typeInto, reveal, open } = r

await open('/vacation')
await page.waitForLoadState('networkidle')
await caption('Согласование отпусков', 'Инструкция для руководителя подразделения')
await pause(3400)

await caption('Шаг 1. Откройте вкладку «Согласование»', 'Цифра рядом — сколько заявок ждут решения')
await clickOn(page.getByRole('button', { name: /Согласование/ }).first())
await page.locator('[data-testid="approval-card"]').first().waitFor()
await page.waitForLoadState('networkidle')
await pause(1500)
await caption('Здесь все заявки ваших сотрудников, ожидающие решения', 'Их можно отфильтровать по отделу, типу отпуска и ФИО')
await moveTo(page.getByPlaceholder('Поиск по ФИО'))
await pause(3500)

const card = page.locator('[data-testid="approval-card"]', { hasText: '16.11.2026' }).first()
await caption('Шаг 2. Нажмите на заявку, чтобы открыть подробности')
await clickOn(card.locator('button').first())
const modal = page.locator('[data-testid="vacation-detail-modal"]')
await modal.waitFor()
await pause(1500)
const overlap = modal.getByText('Пересечение с другими отпусками')
await overlap.evaluate((el) => el.closest('.rounded-lg')?.scrollIntoView({ behavior: 'smooth', block: 'end' }))
await pause(1100)
await caption('Если отпуск пересекается с другими сотрудниками, вы увидите, с кем и когда', '', 'top')
await moveTo(overlap)
await pause(4500)
await page.keyboard.press('Escape')
await modal.waitFor({ state: 'detached' })
await pause(1000)

await caption('Шаг 3. Чтобы отклонить заявку, нажмите «Отклонить» и укажите причину')
await clickOn(card.getByRole('button', { name: 'Отклонить', exact: true }))
await pause(900)
await typeInto(card.getByPlaceholder('Причина отклонения...'), 'Пересекается с отпуском Морозовой О. В., выберите другие даты')
await pause(1200)
await clickOn(card.getByRole('button', { name: 'Отклонить заявку' }))
await pause(2500)
await caption('Сотрудник получит уведомление с причиной отказа')
await pause(3000)

const transferCard = page.locator('[data-testid="approval-card"]', { hasText: '02.11.2026' }).first()
await reveal(transferCard)
await caption('Шаг 4. Чтобы согласовать заявку, нажмите «Одобрить»', 'Так же согласуются и переносы отпуска')
await moveTo(transferCard)
await pause(2500)
await clickOn(transferCard.getByRole('button', { name: 'Одобрить', exact: true }))
await pause(2500)
await caption('Готово! Заявка согласована', 'Отпуск появится в календаре, дни спишутся с баланса сотрудника')
await pause(4200)

console.log(JSON.stringify(await r.finish()))
