import path from 'node:path'
import { startRecording } from '../lib.mjs'

const r = await startRecording('vacation-create', 'ivanov@example.com')
const { page, pause, caption, moveTo, clickOn, typeInto, reveal, smoothScrollTo, dayCell, open } = r

await open('/dashboard')
await caption('Как оформить заявку на отпуск', 'Инструкция для сотрудника: заявка и скачивание заявления')
await pause(3200)

await caption('Шаг 1. Откройте раздел «Отпуск» в меню слева')
await pause(1200)
await clickOn(page.getByRole('link', { name: 'Отпуск', exact: true }).first())
await page.waitForSelector('[data-testid="month-card"]')
await page.waitForLoadState('networkidle')
await pause(1200)

await caption('Шаг 2. Проверьте, сколько дней отпуска у вас доступно')
await moveTo(page.getByText('Доступно к запросу').first())
await pause(3200)

await caption('Шаг 3. Ниже находится календарь отпусков')
await smoothScrollTo(page.getByRole('button', { name: 'Мои отпуска' }), 'start')
await page.evaluate(() => window.scrollBy({ top: -90, behavior: 'smooth' }))
await pause(900)
await moveTo(page.getByRole('button', { name: 'Мои отпуска' }))
await caption('«Мои отпуска» — в календаре видны только ваши отпуска', 'Переключитесь на «Вся команда», чтобы видеть отпуска коллег своего отдела')
await pause(3800)
await clickOn(page.getByRole('button', { name: 'Вся команда' }))
await page.waitForLoadState('networkidle')
await pause(1200)
await caption('«Вся команда» — отпуска коллег отдела', 'Наведите курсор на день, чтобы увидеть, кто отдыхает')
await moveTo(dayCell('Ноябрь', '20'))
await pause(3500)

await caption('Шаг 4. Нажмите на первый день отпуска', 'Заявление подаётся не позднее чем за 14 дней до начала')
await pause(1200)
await clickOn(dayCell('Ноябрь', '16'))
await pause(1200)
await caption('Шаг 5. Нажмите на последний день отпуска')
await pause(900)
await clickOn(dayCell('Ноябрь', '29'))
const modalTitle = page.getByRole('heading', { name: 'Создать заявку на отпуск' })
await modalTitle.waitFor()
await pause(1400)

await caption('Шаг 6. Проверьте период и тип отпуска', 'Количество дней считается автоматически')
await moveTo(page.locator('#vacationType'))
await pause(3000)

const warning = page.getByText('Внимание: пересечение отпусков')
await warning.waitFor({ timeout: 10000 })
await reveal(warning)
await caption('Если в эти даты отдыхает коллега, с которым нельзя уходить одновременно, система покажет, кто это и когда', 'Заявку всё равно можно отправить — решение примет руководитель', 'top')
await moveTo(warning)
await pause(5500)

await caption('Шаг 7. Если нужна оплата проезда — отметьте «С проездом»', 'Доступно раз в два года', 'top')
await clickOn(page.locator('#hasTravel'))
await pause(900)
await typeInto(page.locator('#travelDestination'), 'Сочи')
await pause(900)
await caption('Если едете без детей — просто оставьте список детей пустым', 'Проезд оформится только на вас', 'top')
await moveTo(page.getByText('Нет детей для проезда'))
await pause(3800)
await caption('Если едете с детьми до 18 лет — нажмите «Добавить ребёнка»', 'Укажите ФИО и дату рождения каждого ребёнка', 'top')
await clickOn(page.getByRole('button', { name: 'Добавить ребёнка' }))
await pause(700)
await typeInto(page.getByPlaceholder('ФИО ребёнка').first(), 'Иванова Мария Ивановна', 45)
const birth = page.locator('input[type="date"]').first()
await clickOn(birth)
await birth.fill('2016-05-12')
await pause(2200)

await caption('Шаг 8. Добавьте замещающего на время отпуска', 'Замещающий получит уведомление', 'top')
await clickOn(page.getByRole('button', { name: /Добавить замещение/ }))
const pickerSearch = page.getByPlaceholder('Поиск работника...')
await pickerSearch.waitFor()
await pause(1000)
await typeInto(pickerSearch, 'Кузнецов', 80)
await pause(900)
await clickOn(page.locator('label', { hasText: 'Кузнецов' }).first())
await pause(900)
await clickOn(page.getByRole('button', { name: 'Добавить', exact: true }))
await pause(1500)
await caption('Замещающий добавлен — его инициалы появились под кнопкой', '', 'top')
await moveTo(page.getByRole('button', { name: /Замещающих: 1/ }))
await pause(2600)

await caption('При необходимости оставьте комментарий', '', 'top')
await typeInto(page.locator('#comment'), 'Ежегодный отпуск')
await pause(1200)

await caption('Шаг 9. Нажмите «Создать заявку»', 'Заявка уйдёт руководителю на согласование', 'top')
await pause(1000)
await clickOn(page.getByRole('button', { name: 'Создать заявку' }))
await modalTitle.waitFor({ state: 'detached' })
await page.waitForLoadState('networkidle')
await pause(1000)
await caption('Готово! Заявка отправлена на согласование', 'Статус виден в календаре и в разделе «Мои заявки»')
await moveTo(dayCell('Ноябрь', '17'))
await pause(3500)

await caption('Скачивание заявления', 'Готовое заявление можно скачать в формате Word')
await smoothScrollTo(page.getByRole('heading', { name: 'Отпуска' }).first(), 'center')
await pause(1800)
await caption('Откройте вкладку «Заявления»')
await clickOn(page.getByRole('button', { name: 'Заявления', exact: true }))
await pause(1400)
await caption('Выберите «Заявление на отпуск»')
await clickOn(page.getByRole('button', { name: /Заявление на отпуск/ }))
await page.getByRole('button', { name: 'Скачать .docx' }).waitFor()
await page.waitForLoadState('networkidle')
await pause(1200)
await caption('Проверьте год и шаблон и нажмите «Скачать .docx»', 'В заявление попадут ФИО, должность и все отпуска за выбранный год')
await pause(2600)
const downloadPromise = page.waitForEvent('download')
await clickOn(page.getByRole('button', { name: 'Скачать .docx' }))
const download = await downloadPromise
await download.saveAs(path.join(r.outDir, 'zayavlenie.docx'))
await pause(1200)
await caption('Готово! Заявление скачано', 'Распечатайте, подпишите и передайте в отдел кадров')
await pause(4000)

console.log(JSON.stringify(await r.finish()))
